-- ── UPDATED SCHEDULE (40 route-weeks, all Mondays) ──
-- Run this to replace the old schedule with Monday-based dates
DELETE FROM schedule;

DO $$
DECLARE
  rid UUID;
  cid UUID;
BEGIN
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 1 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-03-02', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 1 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-03-09', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 1 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-03-16', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 1 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-03-23', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 1 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-03-30', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 2 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-04-06', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 2 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-04-13', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 2 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-04-20', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 2 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-04-27', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 2 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-05-04', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 3 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-05-11', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 3 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-05-18', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 3 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-05-25', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 3 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-06-01', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 3 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-06-08', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 4 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-06-15', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 4 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-06-22', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 4 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-06-29', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 4 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-07-06', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 4 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-07-13', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 5 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-07-20', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 5 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-07-27', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 5 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-08-31', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 5 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-09-07', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 5 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-09-14', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 6 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-09-21', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 6 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-09-28', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 6 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-10-05', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 6 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-10-12', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 6 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-10-19', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 7 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-10-26', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 7 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-11-02', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 7 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-11-09', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 7 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-11-16', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 7 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-11-23', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 1';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 8 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-11-30', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 2';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 8 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-12-07', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 3';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 8 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-12-14', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΑΘΗΝΑ 4';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 8 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-12-21', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
  SELECT id INTO rid FROM routes WHERE name = 'ΕΥΒΟΙΑ';
  SELECT id INTO cid FROM cycles WHERE cycle_number = 8 AND year = 2026;
  INSERT INTO schedule (visit_date, route_id, cycle_id) VALUES ('2026-12-28', rid, cid) ON CONFLICT (visit_date) DO NOTHING;
END $$;